### ISSUE TITLE
Swagger spec generation

### ISSUE THREAD

**Issue by roman-mazur** [stanfy/helium#111]
This should provide nice docs and more code generators.

**Comment by Vandalko** [comment]
```
    body multipart('form-data') {
      publickey file()
    }
```

triggers

```
Caused by: java.lang.NullPointerException
	at com.stanfy.helium.swagger.SwaggerHandler.resolveDefinition(SwaggerHandler.java:140)
	at com.stanfy.helium.swagger.SwaggerHandler.body(SwaggerHandler.java:183)
	at com.stanfy.helium.swagger.SwaggerHandler.buildSwagger(SwaggerHandler.java:110)
	at com.stanfy.helium.swagger.SwaggerHandler.handle(SwaggerHandler.java:63)

```

**Comment by roman-mazur** [comment]
Could you give an expected piece of swagger spec?

**Comment by Vandalko** [comment]
```
        "parameters": [
          {
            "name": "publickey",
            "in": "formData",
            "required": true,
            "type": "file"
          }
        ],
        "consumes": ["multipart/form-data"],
```

**Comment by Vandalko** [comment]
Info block requires version declaration in order to pass validation
```json
  "info": {
    "title": "Example API",
   "version": "1.0.0"
  },
```
